version: '3.9'
services:
  app:
    build: .
    container_name: coupongen-app
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - DEFAULT_TENANT_SLUG=${DEFAULT_TENANT_SLUG:-default}
      - ENFORCE_TENANT_PREFIX=${ENFORCE_TENANT_PREFIX:-false}
      - UPLOAD_MAX_BYTES=${UPLOAD_MAX_BYTES:-2097152}
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: coupongen-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:


